### PR TITLE
Fix Invisible first column is too wide

### PR DESCRIPTION
**Pull request by promatik**
Fix for https://github.com/Laravel-Backpack/CRUD/issues/3939

### CODE REVIEW

**Comment by tabacitu** [comment]
Thank you @promatik . Is this a breaking change? Should we only use this for 4.2 or is it ok for 4.1 too?

**Comment by promatik** [comment]
@tabacitu yes, it's a Breaking Change!

image

**Comment by tabacitu** [comment]
Let's move all these files to backpack/CRUD please 🙏

**Comment by promatik** [comment]
Closing this one, and moving things back to backpack with #101.

**Pull request closed without merging**
